[package]
name = "game_of_life"
version = "0.1.0"
authors = ["Isak Jägberg <ijagberg@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.1.6"
structopt = "0.3.7"
coord = { git = "https://github.com/ijagberg/coord" }
ggez = "0.5.1"
