[package]
name = "game_of_life"
version = "0.1.0"
authors = ["Isak Jägberg <ijagberg@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5.0-rc.2"
cgmath = { version = "0.17", features = ["mint"]}
clap = "2.33.0"
regex = "1.1.6"